### ISSUE TITLE
[Bug] That's One Curious Bug.

### ISSUE THREAD

**Issue by NEONBLUETROOPER** [mortuusars/Scholar#7]
Hello Mortuursars! I like your mods and how Scholar improves the Book & Quill greatly. Some of mods gave me the impression that it seemingly fits well into Minecraft itself.

I found a bug when I was experimenting with different mods and found an issue related to the Book and Quill on a lectern and the inventory variant for the mod Curious. Whenever I type the letter 'G', it closes the book and erase new inputted characters on there.
I can only assume that the reason why this is happening is due to the code is thinking that I am opening the Curious Inventory.
Keep in mind that I discovered this bug yesterday (around 13 hours ago).

Here is a bullet point version if needed:
- Bug occurs when Curious is downloaded.
- Happens when using a Book & Quill on a Lectern.
- When 'G' is pressed, the lectern UI is exited. (erases new inputted characters in the process)
- Likely due to it being the keybind for the 'Curious' inventory.
- Discovered around 13 hours ago.

Regardless, I enjoy your mods and I hope you continue on giving everyone some more exciting additions and mods like you have done before.

**Comment by mortuusars** [comment]
Pressing `G` does close Scholar lectern screen, as is does with every screen. But it's not a problem usually, as Scholar does not let you edit books placed on a Lectern. 

Lectern edit screen you have is probably from [Amendments](https://www.curseforge.com/minecraft/mc-mods/amendments)
And it does in fact have the bug you described.

**Comment by NEONBLUETROOPER** [comment]
I in-fact have Amendments installed mostly for decorative reasons for the modpack. The first impression simply makes one suspect that it was a different mod.

I know this is off topic but what if Minecraft Mod management is like Terraria's (TModLoader)?

**Comment by mortuusars** [comment]
I'm don't have sufficient experience and knowledge to answer your question, I'm not connected in any way to Forge or Fabric development. 
You'd be better off asking this question in their discords or issue trackers.

Closing this issue since it's not related to Scholar.

**Comment by NEONBLUETROOPER** [comment]
Understandable. Regardless, I hope to see more promising mods from you in the future along with any possible updates! I hope you are currently enjoying what you are doing and take as much time as you require. :)
